### ISSUE TITLE
unable to run hiFun locally

### ISSUE THREAD

**Issue by Rohit-Satyam** [Junwu302/HiFun#2]
Hi @Junwu302 

I tried running HiFun locally by creating environment as follows: `mamba env create -f env.yml`

The env.yml contained the dependencies you mentioned in README
```
name: hifun
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
 - python=3.6.13
 - tensorflow=2.4.1
 - keras=2.4.3
 - fasttext=0.9.2
 - joblib=1.0.1
 - numpy=1.19.5
 - pandas=1.1.5
 - scikit-learn=0.24.2
 - pip
 - pip:
         - keras-self-attention==0.51.0

```

However I get the following error now:

```
Traceback (most recent call last):
  File "predict.py", line 15, in <module>
    from keras.models import load_model
  File "/home/subudhak/miniconda3/envs/hifun/lib/python3.6/site-packages/keras/__init__.py", line 3, in <module>
    from tensorflow.keras.layers.experimental.preprocessing import RandomRotation
  File "/home/subudhak/miniconda3/envs/hifun/lib/python3.6/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/subudhak/miniconda3/envs/hifun/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 41, in <module>
    from tensorflow.python.eager import context
  File "/home/subudhak/miniconda3/envs/hifun/lib/python3.6/site-packages/tensorflow/python/eager/context.py", line 28, in <module>
    from absl import logging
  File "/home/subudhak/miniconda3/envs/hifun/lib/python3.6/site-packages/absl/logging/__init__.py", line 97, in <module>
    from absl import flags
  File "/home/subudhak/miniconda3/envs/hifun/lib/python3.6/site-packages/absl/flags/__init__.py", line 35, in <module>
    from absl.flags import _argument_parser
  File "/home/subudhak/miniconda3/envs/hifun/lib/python3.6/site-packages/absl/flags/_argument_parser.py", line 82, in <module>
    class ArgumentParser(Generic[_T], metaclass=_ArgumentParserCache):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

```

Kindly help.

**Comment by Rohit-Satyam** [comment]
@Junwu302 anything?
